import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  ArrowLeft,
  Check,
  CheckCircle2,
  ExternalLink,
  Loader2,
  Pencil,
  RefreshCw,
  Send,
  ShieldCheck,
  Sparkles,
  X,
  XCircle,
} from 'lucide-react'
import { ApiError, api } from '../lib/api'
import type {
  ReplyLength,
  ReplyTone,
  ReplyValidationChecks,
  ReplyValidationResult,
  Review,
} from '../lib/types'
import { useBusiness } from '../context/BusinessContext'
import { useReviews } from '../context/ReviewsContext'
import { useToast } from '../context/ToastContext'
import { Avatar } from '../components/Avatar'
import { RatingStars } from '../components/RatingStars'
import { StatusBadge } from '../components/StatusBadge'
import { ReplyControls } from '../components/ReplyControls'
import { ReplyEditorModal } from '../components/ReplyEditorModal'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { EmptyState } from '../components/EmptyState'
import { ErrorState } from '../components/ErrorState'
import { formatFullDate, formatRelativeDate, googleMapsUrl } from '../lib/utils'

export function ReviewDetailPage({ onAuthExpired }: { onAuthExpired: () => void }) {
  const { reviewId = '' } = useParams()
  const navigate = useNavigate()
  const toast = useToast()
  const { business } = useBusiness()
  const locationId = business?.location_id ?? null
  const { getReview, loading: listLoading, applyReviewUpdate, refresh } = useReviews()

  const [review, setReview] = useState<Review | undefined>(() => getReview(reviewId))
  const [reply, setReply] = useState('')
  const [edited, setEdited] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [generateError, setGenerateError] = useState<string | null>(null)
  const [tone, setTone] = useState<ReplyTone>('Friendly & Professional')
  const [length, setLength] = useState<ReplyLength>('Medium')
  const [editorOpen, setEditorOpen] = useState(false)
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [posting, setPosting] = useState(false)
  // Manual "Check Reply" result, stored with the exact text that was checked so
  // a result is never shown for a different (regenerated or edited) draft.
  const [validationResult, setValidationResult] = useState<{
    text: string
    result: ReplyValidationResult
  } | null>(null)
  const [validating, setValidating] = useState(false)
  const [validationError, setValidationError] = useState<string | null>(null)
  const autoGenerated = useRef(false)

  const clearValidation = useCallback(() => {
    setValidationResult(null)
    setValidationError(null)
  }, [])

  // Keep local review synced with context once the list resolves.
  useEffect(() => {
    const fromContext = getReview(reviewId)
    if (fromContext) setReview(fromContext)
  }, [getReview, reviewId])

  const handleAuthError = useCallback(
    (err: unknown): boolean => {
      if (err instanceof ApiError && err.isAuth) {
        onAuthExpired()
        navigate('/login')
        return true
      }
      return false
    },
    [onAuthExpired, navigate],
  )

  const generate = useCallback(
    async (opts?: { silent?: boolean }) => {
      setGenerating(true)
      setGenerateError(null)
      clearValidation()
      try {
        const res = await api.generateReply(reviewId, { locationId, tone, length })
        setReply(res.reply)
        setEdited(false)
        setReview((current) => current ?? res.review)
        if (!opts?.silent) toast.success('AI reply generated.')
      } catch (err) {
        if (handleAuthError(err)) return
        const message =
          err instanceof ApiError ? err.message : 'Could not generate a reply.'
        setGenerateError(message)
        toast.error(message)
      } finally {
        setGenerating(false)
      }
    },
    [reviewId, locationId, tone, length, toast, handleAuthError, clearValidation],
  )

  const checkReply = async () => {
    if (validating || !reply) return
    const text = reply
    setValidating(true)
    setValidationError(null)
    try {
      const result = await api.validateReply(reviewId, text, locationId)
      setValidationResult({ text, result })
    } catch (err) {
      if (handleAuthError(err)) return
      const alreadyAnswered = err instanceof ApiError && err.status === 409
      const message = alreadyAnswered ? err.message : 'Could not validate the reply.'
      setValidationResult(null)
      setValidationError(message)
      toast.error(message)
      // Answered elsewhere: resync so the page switches to the posted reply.
      if (alreadyAnswered) void refresh()
    } finally {
      setValidating(false)
    }
  }

  // Auto-generate the first draft for unanswered reviews (once).
  useEffect(() => {
    if (autoGenerated.current) return
    if (listLoading) return
    if (!review) return
    if (review.has_reply) return
    autoGenerated.current = true
    void generate({ silent: true })
  }, [listLoading, review, generate])

  const publish = async (text: string) => {
    if (posting) return
    setPosting(true)
    try {
      const res = await api.publishReply(reviewId, text, locationId)
      if (review) {
        applyReviewUpdate({
          ...review,
          has_reply: true,
          reply_comment: res.reply ?? text,
          reply_updated_at: new Date().toISOString(),
        })
      }
      toast.success('Reply posted to Google.')
      setEditorOpen(false)
      setConfirmOpen(false)
      void refresh()
      navigate('/dashboard')
    } catch (err) {
      if (handleAuthError(err)) return
      const message = err instanceof ApiError ? err.message : 'Could not post the reply.'
      toast.error(message)
      // If it was already answered elsewhere, resync and leave the detail view.
      if (err instanceof ApiError && err.status === 409) {
        void refresh()
        navigate('/dashboard')
      }
      setConfirmOpen(false)
    } finally {
      setPosting(false)
    }
  }

  // --- Render states ------------------------------------------------------
  if (listLoading && !review) {
    return <DetailSkeleton />
  }

  if (!review) {
    return (
      <div className="space-y-4">
        <BackLink onClick={() => navigate('/dashboard')} />
        <EmptyState
          icon={Sparkles}
          title="Review not found"
          description="This review may have been removed or is no longer available."
          action={
            <button className="btn-primary" onClick={() => navigate('/dashboard')}>
              Back to Reviews
            </button>
          }
        />
      </div>
    )
  }

  const alreadyReplied = review.has_reply
  const currentValidation =
    validationResult && validationResult.text === reply ? validationResult.result : null
  const googleUrl = business ? googleMapsUrl(business.name, business.address) : undefined

  return (
    <div className="space-y-5">
      <BackLink onClick={() => navigate(-1)} />

      <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
        {/* LEFT: customer review */}
        <div className="space-y-5">
          <section className="card p-5">
            <h2 className="text-sm font-bold text-slate-900">Customer Review</h2>
            <div className="mt-4 flex items-start gap-3">
              <Avatar name={review.reviewer} photoUrl={review.profile_photo_url} size="lg" />
              <div className="min-w-0">
                <h3 className="text-sm font-semibold text-slate-900">{review.reviewer}</h3>
                <p className="text-xs text-slate-400">
                  {formatRelativeDate(review.created_at)}
                </p>
                <div className="mt-1">
                  <RatingStars rating={review.rating} size="md" />
                </div>
              </div>
            </div>

            {review.review ? (
              <p className="mt-4 text-sm leading-relaxed text-slate-600">{review.review}</p>
            ) : (
              <p className="mt-4 text-sm italic text-slate-400">
                (No written comment — rating only)
              </p>
            )}

            {googleUrl && (
              <a
                href={googleUrl}
                target="_blank"
                rel="noreferrer"
                className="mt-4 inline-flex items-center gap-1.5 text-xs font-medium text-slate-500 hover:text-brand-600"
              >
                <ExternalLink className="h-3.5 w-3.5" />
                View on Google
              </a>
            )}
          </section>

          <section className="card p-5">
            <h2 className="text-sm font-bold text-slate-900">Review Details</h2>
            <dl className="mt-4 space-y-3 text-sm">
              <DetailRow label="Rating">
                <RatingStars rating={review.rating} size="sm" />
              </DetailRow>
              <DetailRow label="Date">
                <span className="text-slate-700">{formatFullDate(review.created_at) || '—'}</span>
              </DetailRow>
              <DetailRow label="Review ID">
                <span className="max-w-[180px] truncate font-mono text-xs text-slate-500">
                  {review.review_id}
                </span>
              </DetailRow>
              <DetailRow label="Status">
                <StatusBadge status={alreadyReplied ? 'replied' : 'needs-reply'} />
              </DetailRow>
            </dl>
          </section>
        </div>

        {/* RIGHT: AI reply / posted reply */}
        <section className="card flex flex-col p-5">
          {alreadyReplied ? (
            <AlreadyRepliedPanel review={review} />
          ) : (
            <>
              <div className="flex items-center justify-between">
                <h2 className="flex items-center gap-2 text-sm font-bold text-slate-900">
                  <Sparkles className="h-4 w-4 text-brand-500" />
                  AI Generated Reply
                </h2>
                <button
                  onClick={() => generate()}
                  disabled={generating || posting || validating}
                  className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand-600 hover:text-brand-700 disabled:opacity-50"
                >
                  <RefreshCw className={generating ? 'h-3.5 w-3.5 animate-spin' : 'h-3.5 w-3.5'} />
                  Regenerate
                </button>
              </div>

              {/* Reply area */}
              <div className="mt-4">
                {generating && !reply ? (
                  <div className="flex min-h-[180px] flex-col items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-center">
                    <span className="h-6 w-6 animate-spin rounded-full border-2 border-brand-200 border-t-brand-600" />
                    <p className="mt-3 text-sm font-medium text-slate-500">
                      Generating reply…
                    </p>
                  </div>
                ) : generateError && !reply ? (
                  <ErrorState
                    title="Couldn’t generate a reply"
                    message={generateError}
                    onRetry={() => generate()}
                    retrying={generating}
                  />
                ) : (
                  <div className="relative">
                    <div className="min-h-[180px] whitespace-pre-wrap rounded-lg border border-slate-200 bg-slate-50/70 px-4 py-3.5 text-sm leading-relaxed text-slate-700">
                      {reply || 'No reply yet. Click Regenerate to create one.'}
                    </div>
                    {generating && (
                      <div className="absolute inset-0 flex items-center justify-center rounded-lg bg-white/60">
                        <span className="h-6 w-6 animate-spin rounded-full border-2 border-brand-200 border-t-brand-600" />
                      </div>
                    )}
                    {edited && (
                      <span className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-slate-400">
                        <Pencil className="h-3 w-3" /> Edited manually
                      </span>
                    )}
                  </div>
                )}
              </div>

              {/* Controls */}
              <div className="mt-4">
                <ReplyControls
                  tone={tone}
                  length={length}
                  onToneChange={setTone}
                  onLengthChange={setLength}
                  disabled={generating || posting}
                />
              </div>

              <button
                onClick={() => generate()}
                disabled={generating || posting || validating}
                className="btn-primary mt-4 w-full"
              >
                <RefreshCw className={generating ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} />
                {generating ? 'Generating…' : 'Regenerate Reply'}
              </button>

              <button
                onClick={() => void checkReply()}
                disabled={!reply || generating || posting || validating}
                className="btn-secondary mt-3 w-full"
              >
                {validating ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <ShieldCheck className="h-4 w-4" />
                )}
                {validating ? 'Checking…' : 'Check Reply'}
              </button>

              {currentValidation ? (
                <ValidationResultCard result={currentValidation} />
              ) : (
                validationError && (
                  <p className="mt-3 rounded-lg bg-rose-50 px-3.5 py-2.5 text-xs font-medium text-rose-600">
                    {validationError}
                  </p>
                )
              )}

              <div className="mt-3 grid grid-cols-2 gap-3">
                <button
                  onClick={() => setEditorOpen(true)}
                  disabled={!reply || generating || posting || validating}
                  className="btn-secondary"
                >
                  <Pencil className="h-4 w-4" />
                  Edit Manually
                </button>
                <button
                  onClick={() => setConfirmOpen(true)}
                  disabled={!reply || generating || posting}
                  className="btn-primary"
                >
                  <Send className="h-4 w-4" />
                  {posting ? 'Posting…' : 'Post Reply'}
                </button>
              </div>
            </>
          )}
        </section>
      </div>

      <ReplyEditorModal
        open={editorOpen}
        initialText={reply}
        tone={tone}
        length={length}
        posting={posting}
        onToneChange={setTone}
        onLengthChange={setLength}
        onCancel={() => {
          if (!posting) setEditorOpen(false)
        }}
        onPost={(text) => {
          if (text !== reply) clearValidation()
          setReply(text)
          setEdited(true)
          void publish(text)
        }}
      />

      <ConfirmDialog
        open={confirmOpen}
        title="Post this reply to Google?"
        description="This reply will be published publicly on your Google Business Profile. You can edit it later on Google if needed."
        confirmLabel="Post Reply"
        busy={posting}
        onConfirm={() => void publish(reply)}
        onCancel={() => {
          if (!posting) setConfirmOpen(false)
        }}
      />
    </div>
  )
}

function AlreadyRepliedPanel({ review }: { review: Review }) {
  return (
    <>
      <h2 className="flex items-center gap-2 text-sm font-bold text-slate-900">
        <CheckCircle2 className="h-4 w-4 text-emerald-500" />
        Your Posted Reply
      </h2>
      <div className="mt-4 min-h-[180px] whitespace-pre-wrap rounded-lg border border-emerald-100 bg-emerald-50/60 px-4 py-3.5 text-sm leading-relaxed text-slate-700">
        {review.reply_comment || 'A reply has been posted for this review.'}
      </div>
      {review.reply_updated_at && (
        <p className="mt-3 text-xs text-slate-400">
          Replied on {formatFullDate(review.reply_updated_at)}
        </p>
      )}
      <p className="mt-4 rounded-lg bg-slate-50 px-3.5 py-3 text-xs text-slate-500">
        This review has already been answered on Google, so no new reply can be generated.
      </p>
    </>
  )
}

const CHECK_LABELS: Record<keyof ReplyValidationChecks, string> = {
  review_relevance: 'Review relevance',
  business_relevance: 'Business relevance',
  no_hallucination: 'No hallucination',
  appropriate_tone: 'Appropriate tone',
  safe_to_publish: 'Safe to publish',
}

function ValidationResultCard({ result }: { result: ReplyValidationResult }) {
  const passed = result.passed
  const Icon = passed ? CheckCircle2 : XCircle
  return (
    <div
      className={
        passed
          ? 'mt-3 rounded-lg border border-emerald-200 bg-emerald-50/60 px-4 py-3'
          : 'mt-3 rounded-lg border border-rose-200 bg-rose-50/60 px-4 py-3'
      }
    >
      <p
        className={
          passed
            ? 'flex items-center gap-2 text-sm font-semibold text-emerald-700'
            : 'flex items-center gap-2 text-sm font-semibold text-rose-700'
        }
      >
        <Icon className="h-4 w-4" />
        {passed ? 'Reply Passed' : 'Reply Failed'}
      </p>
      <p className="mt-1 text-xs leading-relaxed text-slate-600">
        {passed
          ? 'This reply is suitable for this review.'
          : result.reason || 'This reply may not be suitable for this review.'}
      </p>
      <ul className="mt-2.5 grid grid-cols-1 gap-x-4 gap-y-1 text-xs sm:grid-cols-2">
        {(Object.keys(CHECK_LABELS) as (keyof ReplyValidationChecks)[]).map((key) => {
          const ok = result.checks[key]
          return (
            <li key={key} className="flex items-center justify-between gap-2">
              <span className="text-slate-500">{CHECK_LABELS[key]}</span>
              {ok ? (
                <Check className="h-3.5 w-3.5 text-emerald-600" aria-label="passed" />
              ) : (
                <X className="h-3.5 w-3.5 text-rose-600" aria-label="failed" />
              )}
            </li>
          )
        })}
      </ul>
    </div>
  )
}

function DetailRow({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex items-center justify-between gap-3">
      <dt className="text-slate-500">{label}</dt>
      <dd className="flex items-center">{children}</dd>
    </div>
  )
}

function BackLink({ onClick }: { onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-brand-600"
    >
      <ArrowLeft className="h-4 w-4" />
      Back to Reviews
    </button>
  )
}

function DetailSkeleton() {
  return (
    <div className="space-y-5">
      <div className="h-5 w-32 animate-pulse rounded bg-slate-200" />
      <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
        <div className="card h-64 animate-pulse" />
        <div className="card h-80 animate-pulse" />
      </div>
    </div>
  )
}
