"""Reply generation with provider fallback: Groq primary, Gemini fallback.

Flow (one attempt per provider, no retry loops):

    Groq ── success ──> return reply          (Gemini is never called)
      │
    failure (not configured, API error, 429, timeout, empty reply, ...)
      │
    Gemini ── success ──> return reply
      │
    failure / not configured ──> ReplyGenerationError

Provider-specific exceptions stay inside the AI layer; callers only ever see
:class:`ReplyGenerationError`, whose message is safe to show to end users.
"""

from __future__ import annotations

import logging
from typing import Any

from app.ai.gemini_client import GeminiError, generate_review_reply_gemini
from app.ai.groq_client import GroqError, generate_review_reply_groq
from app.config import settings

logger = logging.getLogger(__name__)


class ReplyGenerationError(Exception):
    """Every available AI provider failed; the message is user-safe."""


def generate_review_reply(
    review: dict[str, Any],
    tone: str | None = None,
    length: str | None = None,
    revision_feedback: str | None = None,
) -> str:
    """Generate a reply draft with Groq, falling back to Gemini on failure.

    Same arguments as the provider functions (see
    :func:`app.ai.prompts.build_user_prompt`). Returns the reply text or
    raises :class:`ReplyGenerationError`. Never publishes anything.
    """
    reply, _provider = generate_review_reply_with_provider(
        review, tone=tone, length=length, revision_feedback=revision_feedback
    )
    return reply


def generate_review_reply_with_provider(
    review: dict[str, Any],
    tone: str | None = None,
    length: str | None = None,
    revision_feedback: str | None = None,
) -> tuple[str, str]:
    """Like :func:`generate_review_reply`, also returning the provider used.

    The provider is ``"groq"`` or ``"gemini"`` (for automation run logs).
    """
    review_id = review.get("review_id") or "?"
    try:
        reply = generate_review_reply_groq(
            review, tone=tone, length=length, revision_feedback=revision_feedback
        )
    except GroqError as groq_error:
        if not settings.gemini_api_key:
            logger.error(
                "Review %s: Groq (%s) failed: %s; no Gemini fallback configured",
                review_id, settings.groq_model, groq_error,
            )
            raise ReplyGenerationError(
                "Reply generation failed and no fallback AI provider is "
                "configured. Please try again later."
            ) from groq_error
        logger.warning(
            "Review %s: Groq (%s) failed: %s; falling back to Gemini",
            review_id, settings.groq_model, groq_error,
        )
    else:
        logger.info("Review %s: reply generated by Groq (%s)", review_id, settings.groq_model)
        return reply, "groq"

    try:
        reply = generate_review_reply_gemini(
            review, tone=tone, length=length, revision_feedback=revision_feedback
        )
    except GeminiError as gemini_error:
        logger.error(
            "Review %s: Gemini (%s) failed: %s; reply generation failed",
            review_id, settings.gemini_model, gemini_error,
        )
        raise ReplyGenerationError(
            "Reply generation is temporarily unavailable. Please try again "
            "in a moment."
        ) from gemini_error
    logger.info("Review %s: reply generated by Gemini (%s)", review_id, settings.gemini_model)
    return reply, "gemini"
